### ISSUE TITLE
TTF

### ISSUE THREAD

**Issue by davelab6** [zeynepakay/theruqahproject#6]
Please post a TTF to review, along with build instructions :)

**Comment by davelab6** [comment]
I couldn't find any build instructions, but I imagine it is a regular Glyphs export only.

**Comment by zeynepakay** [comment]
Hi Dave,

Yes it was a Glyphs export, should I add anything else? I updated the Readme file with a longer description as you suggested. I also uploaded the invoice just now. Kalapi is looking over a buggy lookup in the CA feature and should get back to me this weekend. Right now everything works good on a linguistic level, but it would be better if I can get the beh forms to switch up when there is more than one in a row and when there are vowel marks present. I should release an update when that issue is solved, right?

Please let me know if the review turns out alright.

Best,

Z.
